run:
  timeout: 3m # default GitHub action machines really suck, so we need to increase timeout.

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # Additional linters
    - goimports
    - revive

linters-settings:
  goimports:
    local-prefixes: github.com/TomaszDomagala/Allezon
