- name: Setup pv folders
  hosts: all

  tasks:
    - name: Clear pv folders
      file:
        path: "{{item}}"
        state: absent
        mode: '0777'
      with_items:
        - /usr/share/redpanda
        - /usr/share/aerospike
        - /usr/share/elastic

    - name: Create pv folders
      file:
        path: "{{item}}"
        state: directory
        mode: '0777'
      with_items:
        - /usr/share/redpanda
        - /usr/share/aerospike
        - /usr/share/elastic
