---
- name: Fix kubernetes configuration
  hosts: kube_control_plane

  tasks:
  - name: Copy kubernetes config to ansible_remote home
    copy:
      src: /etc/kubernetes/admin.conf
      dest: "/home/{{ ansible_user }}/admin.conf"
      # file should be owned by the user who will use it
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      remote_src: yes
  - name: Add environment variable to .bashrc
    lineinfile:
      path: "/home/{{ ansible_user }}/.bashrc"
      line: "export KUBECONFIG=/home/{{ ansible_user }}/admin.conf"
      state: present
