---
{{- range $v := .Values.storageClass }}

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $v.name }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
{{- end }}

