all:
  hosts:
    node1:
      ansible_host: 10.112.101.101
      ip: 10.112.101.101
      access_ip: 10.112.101.101
    node2:
      ansible_host: 10.112.101.102
      ip: 10.112.101.102
      access_ip: 10.112.101.102
    node3:
      ansible_host: 10.112.101.103
      ip: 10.112.101.103
      access_ip: 10.112.101.103
    node4:
      ansible_host: 10.112.101.104
      ip: 10.112.101.104
      access_ip: 10.112.101.104
    node5:
      ansible_host: 10.112.101.105
      ip: 10.112.101.105
      access_ip: 10.112.101.105
    node6:
      ansible_host: 10.112.101.106
      ip: 10.112.101.106
      access_ip: 10.112.101.106
    node7:
      ansible_host: 10.112.101.107
      ip: 10.112.101.107
      access_ip: 10.112.101.107
    node8:
      ansible_host: 10.112.101.108
      ip: 10.112.101.108
      access_ip: 10.112.101.108
    node9:
      ansible_host: 10.112.101.109
      ip: 10.112.101.109
      access_ip: 10.112.101.109
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
        node6:
        node7:
        node8:
        node9:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
