all:
  hosts:
    node2:
      ansible_host: 10.112.112.102
      ip: 10.112.112.102
      access_ip: 10.112.112.102
    node3:
      ansible_host: 10.112.112.103
      ip: 10.112.112.103
      access_ip: 10.112.112.103
    node4:
      ansible_host: 10.112.112.104
      ip: 10.112.112.104
      access_ip: 10.112.112.104
    node5:
      ansible_host: 10.112.112.105
      ip: 10.112.112.105
      access_ip: 10.112.112.105

  children:
    kube_control_plane:
      hosts:
        node2:
    kube_node:
      hosts:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
