all:
  hosts:
    node1:
      ansible_host: 10.112.101.101
      ip: 10.112.101.101
      access_ip: 10.112.101.101
    node2:
      ansible_host: 10.112.101.102
      ip: 10.112.101.102
      access_ip: 10.112.101.102
    node3:
      ansible_host: 10.112.101.103
      ip: 10.112.101.103
      access_ip: 10.112.101.103
    node4:
      ansible_host: 10.112.101.104
      ip: 10.112.101.104
      access_ip: 10.112.101.104
    node5:
      ansible_host: 10.112.101.105
      ip: 10.112.101.105
      access_ip: 10.112.101.105
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}