all:
  hosts:
    node1:
      ansible_host: 10.112.112.101
      ip: 10.112.112.101
      access_ip: 10.112.112.101
    node2:
      ansible_host: 10.112.112.102
      ip: 10.112.112.102
      access_ip: 10.112.112.102
    node3:
      ansible_host: 10.112.112.103
      ip: 10.112.112.103
      access_ip: 10.112.112.103
    node4:
      ansible_host: 10.112.112.104
      ip: 10.112.112.104
      access_ip: 10.112.112.104
    node5:
      ansible_host: 10.112.112.105
      ip: 10.112.112.105
      access_ip: 10.112.112.105
    node6:
      ansible_host: 10.112.112.106
      ip: 10.112.112.106
      access_ip: 10.112.112.106
    node7:
      ansible_host: 10.112.112.107
      ip: 10.112.112.107
      access_ip: 10.112.112.107
    node8:
      ansible_host: 10.112.112.108
      ip: 10.112.112.108
      access_ip: 10.112.112.108
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
        node4:
        node5:
        node6:
        node7:
        node8:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}