api:
  image:
    tag: "0.2.2"
  replicaCount: 3
  env:
    # Kafka configuration
    - name: KAFKA_NULL_PRODUCER
      value: "false"
    - name: KAFKA_ADDRESSES
      value: "allezon-redpanda-0.allezon-redpanda.default.svc.cluster.local:9093,allezon-redpanda-1.allezon-redpanda.default.svc.cluster.local:9093,allezon-redpanda-2.allezon-redpanda.default.svc.cluster.local:9093"
    - name: KAFKA_NUM_PARTITIONS
      value: "3"
    - name: KAFKA_REPLICATION_FACTOR
      value: "3"
    # Database configuration
    - name: DB_NULL_CLIENT
      value: "false"
    - name: DB_ADDRESSES
      value: "allezon-aerospike-0.allezon-aerospike.default.svc.cluster.local:3000,allezon-aerospike-1.allezon-aerospike.default.svc.cluster.local:3000,allezon-aerospike-2.allezon-aerospike.default.svc.cluster.local:3000"
    # ID Getter configuration
    - name: ID_GETTER_NULL_CLIENT
      value: "false"
    - name: ID_GETTER_ADDRESS
      value: "allezon-idgetter.default.svc.cluster.local:8080"

worker:
  image:
    tag: "0.2.2"
  replicaCount: 3
  env:
    - name: PORT
      value: "8080"
    - name: KAFKA_ADDRESSES
      value: "allezon-redpanda-0.allezon-redpanda.default.svc.cluster.local:9093,allezon-redpanda-1.allezon-redpanda.default.svc.cluster.local:9093,allezon-redpanda-2.allezon-redpanda.default.svc.cluster.local:9093"
    - name: DB_ADDRESSES
      value: "allezon-aerospike-0.allezon-aerospike.default.svc.cluster.local:3000,allezon-aerospike-1.allezon-aerospike.default.svc.cluster.local:3000,allezon-aerospike-2.allezon-aerospike.default.svc.cluster.local:3000"
    - name: ID_GETTER_ADDRESS
      value: "allezon-idgetter.default.svc.cluster.local:8080"

idgetter:
  image:
    tag: "0.2.2"
  replicaCount: 1
  autoscaling:
    enabled: false
  env:
    - name: DB_ADDRESSES
      value: "allezon-aerospike-0.allezon-aerospike.default.svc.cluster.local:3000,allezon-aerospike-1.allezon-aerospike.default.svc.cluster.local:3000,allezon-aerospike-2.allezon-aerospike.default.svc.cluster.local:3000"


redpanda:
  statefulset:
    replicas: 3
  nameOverride: redpanda
  fullnameOverride: redpanda

  storage:
    persistentVolume:
      enabled: true
      storageClass: local-storage-redpanda
      size: 3Gi

  config:
    cluster:
      retention_bytes: 3000000


aerospike:
  dbReplicas: 3 # Change to 3 in real deployment.

  persistenceStorage:
    - enabled: true
      storageClass: local-storage-aerospike
      name: aerospike-data-pv
      mountPath: /opt/aerospike/pv
      volumeMode: Filesystem
      accessMode: ReadWriteOnce
      size: 15Gi
