api:
  image:
    tag: "0.2.2"
  replicaCount: 8
  env:
    # Kafka configuration
    - name: KAFKA_NULL_PRODUCER
      value: "false"
    - name: KAFKA_ADDRESSES
      value: "allezon-redpanda-0.allezon-redpanda.default.svc.cluster.local:9093,allezon-redpanda-1.allezon-redpanda.default.svc.cluster.local:9093,allezon-redpanda-2.allezon-redpanda.default.svc.cluster.local:9093"
    - name: KAFKA_NUM_PARTITIONS
      value: "3"
    - name: KAFKA_REPLICATION_FACTOR
      value: "3"
    # Database configuration
    - name: DB_NULL_CLIENT
      value: "false"
    - name: DB_PROFILES_ADDRESSES
      value: "storage-profiles-aerospike-profiles-0.storage-profiles-aerospike-profiles.default.svc.cluster.local:3000,storage-profiles-aerospike-profiles-1.storage-profiles-aerospike-profiles.default.svc.cluster.local:3000,storage-profiles-aerospike-profiles-2.storage-profiles-aerospike-profiles.default.svc.cluster.local:3000"
    - name: DB_AGGREGATES_ADDRESSES
      value: "storage-aggregates-aerospike-aggregates-0.storage-aggregates-aerospike-aggregates.default.svc.cluster.local:3000,storage-aggregates-aerospike-aggregates-1.storage-aggregates-aerospike-aggregates.default.svc.cluster.local:3000,storage-aggregates-aerospike-aggregates-2.storage-aggregates-aerospike-aggregates.default.svc.cluster.local:3000"
    # ID Getter configuration
    - name: ID_GETTER_NULL_CLIENT
      value: "false"
    - name: ID_GETTER_ADDRESS
      value: "allezon-idgetter.default.svc.cluster.local:8080"

worker:
  image:
    tag: "0.2.2"
  replicaCount: 3
  env:
    - name: PORT
      value: "8080"
    - name: KAFKA_ADDRESSES
      value: "allezon-redpanda-0.allezon-redpanda.default.svc.cluster.local:9093,allezon-redpanda-1.allezon-redpanda.default.svc.cluster.local:9093,allezon-redpanda-2.allezon-redpanda.default.svc.cluster.local:9093"
    - name: DB_ADDRESSES
      value: "storage-aggregates-aerospike-aggregates-0.storage-aggregates-aerospike-aggregates.default.svc.cluster.local:3000,storage-aggregates-aerospike-aggregates-1.storage-aggregates-aerospike-aggregates.default.svc.cluster.local:3000,storage-aggregates-aerospike-aggregates-2.storage-aggregates-aerospike-aggregates.default.svc.cluster.local:3000"
    - name: ID_GETTER_ADDRESS
      value: "allezon-idgetter.default.svc.cluster.local:8080"

idgetter:
  image:
    tag: "0.2.2"
  replicaCount: 1
  autoscaling:
    enabled: false
  env:
    - name: DB_ADDRESSES
      value: "storage-profiles-aerospike-profiles-0.storage-profiles-aerospike-profiles.default.svc.cluster.local:3000,storage-profiles-aerospike-profiles-1.storage-profiles-aerospike-profiles.default.svc.cluster.local:3000,storage-profiles-aerospike-profiles-2.storage-profiles-aerospike-profiles.default.svc.cluster.local:3000"


redpanda:
  statefulset:
    replicas: 3
  nameOverride: redpanda
  fullnameOverride: redpanda

  storage:
    persistentVolume:
      enabled: true
      storageClass: local-storage-redpanda
      size: 3Gi

  config:
    cluster:
      retention_bytes: 3000000
