apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example
spec:
  addresses:
    - {{ .Values.ipPool }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
spec:
