storage:
  - persistentVolumeName: aerospike-pv
    storageClassName: local-storage-aerospike
    nodeHostName: node4
    capacity: 15Gi
    localPath: /usr/share/aerospike
  - persistentVolumeName: redpanda-pv
    storageClassName: local-storage-redpanda
    nodeHostName: node3
    capacity: 3Gi
    localPath: /usr/share/redpanda
  - persistentVolumeName: elk-pv
    storageClassName: local-storage-elk
    nodeHostName: node5
    capacity: 5Gi
    localPath: /usr/share/elastic
