apiVersion: v2
name: elk-operator
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: eck-operator
    version: 2.6.1
    repository: https://helm.elastic.co