name: linters
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  golangci:
    name: golangci
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Checkout
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./src
